rmin: 0.1
rmax: 100
nneighbours: 8
nsamples: 1.e+5
batch_size: 5.e+4
neval: 10000
seed: 42
nbins_marks: 10


################################################################################
#                                 totpartmass                                 #
################################################################################


"mass001":
  primary:
    name:
    - totpartmass,
    - group_mass
    min: 1.e+12
    max: 1.e+13

"mass002":
  primary:
    name:
    - totpartmass,
    - group_mass
    min: 1.e+13
    max: 1.e+14

"mass003":
  primary:
    name:
    - totpartmass,
    - group_mass
    min: 1.e+14


################################################################################
#                        totpartmass + lambda200c                             #
################################################################################


"mass001_spinlow":
  primary:
    name: totpartmass
    min: 1.e+12
    max: 1.e+13
  secondary:
    name: lambda200c
    toperm: false
    marked: true
    max: 0.5

"mass001_spinhigh":
  primary:
    name: totpartmass
    min: 1.e+12
    max: 1.e+13
  secondary:
    name: lambda200c
    toperm: false
    marked: true
    min: 0.5

"mass001_spinmedian_perm":
  primary:
    name: totpartmass
    min: 1.e+12
    max: 1.e+13
  secondary:
    name: lambda200c
    toperm: true
    marked : true
    min: 0.5

"mass002_spinlow":
  primary:
    name: totpartmass
    min: 1.e+13
    max: 1.e+14
  secondary:
    name: lambda200c
    toperm: false
    marked: true
    max: 0.5

"mass002_spinhigh":
  primary:
    name: totpartmass
    min: 1.e+13
    max: 1.e+14
  secondary:
    name: lambda200c
    toperm: false
    marked: true
    min: 0.5

"mass002_spinmedian_perm":
  primary:
    name: totpartmass
    min: 1.e+13
    max: 1.e+14
  secondary:
    name: lambda200c
    toperm: true
    marked : true
    min: 0.5

"mass003_spinlow":
  primary:
    name: totpartmass
    min: 1.e+14
  secondary:
    name: lambda200c
    toperm: false
    marked: true
    max: 0.5

"mass003_spinhigh":
  primary:
    name: totpartmass
    min: 1.e+14
  secondary:
    name: lambda200c
    toperm: false
    marked: true
    min: 0.5

"mass003_spinmedian_perm":
  primary:
    name: totpartmass
    min: 1.e+14
  secondary:
    name: lambda200c
    toperm: true
    marked : true
    min: 0.5


################################################################################
#                           Cross with random                                  #
################################################################################

"mass001_random":
  primary:
    name: totpartmass
    min: 1.e+12
    max: 1.e+13