rmin: 0.1
rmax: 100
nneighbours: 16
nsamples: 1.e+7
batch_size: 1.e+6
neval: 10000
seed: 42
mass_feature: totpartmass


################################################################################
#                                 totpartmass                                 #
################################################################################


"mass001":
  perm: false
  totpartmass:
    min: 1.e+12
    max: null

"mass002":
  perm: false
  totpartmass:
    min: 1.e+13
    max: null

"mass003":
  perm: false
  totpartmass:
    min: 1.e+14
    max: null


################################################################################
#                        totpartmass + lambda200c                             #
################################################################################


"mass001_spinlow":
  perm: false
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    below_median: true


"mass001_spinhigh":
  perm: false
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    below_median: false

"mass001_spinmedian_perm":  # One for both low and high spin since this is a median cut
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    below_median: true
  perm: true

"mass001_spinmedian_cross":
  median_cross: lambda200c
  totpartmass:
    min: 1.e+12
    max: null

"mass002_spinlow":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    below_median: true
  perm: false

"mass002_spinhigh":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    below_median: false
  perm: false

"mass002_spinmedian_perm":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    below_median: false
  perm: true

"mass002_spinmedian_cross":
  median_cross: lambda200c
  totpartmass:
    min: 1.e+13
    max: null

"mass003_spinlow":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    below_median: true
  perm: false

"mass003_spinhigh":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    below_median: false
  perm: false

"mass003_spinmedian_perm":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    below_median: false
  perm: true

"mass003_spinmedian_cross":
  median_cross: lambda200c
  totpartmass:
    min: 1.e+14
    max: null
