rmin: 0.1
rmax: 100
nneighbours: 16
nsamples: 1.e+7
batch_size: 1.e+6
neval: 10000
seed: 42
mass_feature: totpartmass


################################################################################
#                                 totpartmass                                 #
################################################################################


"mass001":
  totpartmass:
    min: 1.e+12
    max: null
  perm: false

"mass001_perm":
  totpartmass:
    min: 1.e+12
    max: null
  perm: true

"mass002":
  totpartmass:
    min: 1.e+13
    max: null
  perm: false

"mass002_perm":
  totpartmass:
    min: 1.e+13
    max: null
  perm: true

"mass003":
  totpartmass:
    min: 1.e+14
    max: null
  perm: false

"mass003_perm":
  totpartmass:
    min: 1.e+14
    max: null
  perm: true


################################################################################
#                        totpartmass + lambda200c                             #
################################################################################


"mass001_spinlow":
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    below_median: true
  perm: false

"mass001_spinlow_perm":
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    below_median: true
  perm: true

"mass001_spinhigh":
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    below_median: false
  perm: false

"mass001_spinhigh_perm":
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    below_median: false
  perm: true

"mass002_spinlow":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    below_median: true
  perm: false

"mass002_spinlow_perm":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    below_median: true
  perm: true

"mass002_spinhigh":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    below_median: false
  perm: false

"mass002_spinhigh_perm":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    below_median: false
  perm: true

"mass003_spinlow":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    below_median: true
  perm: false

"mass003_spinlow_perm":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    below_median: true
  perm: true

"mass_003_spinhigh":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    below_median: false
  perm: false

"mass_003_spinhigh_perm":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    below_median: false
  perm: true
