rmin: 0.1
rmax: 100
nneighbours: 16
nsamples: 1.e+7
batch_size: 1.e+6
neval: 10000
seed: 42


################################################################################
#                                 totpartmass                                 #
################################################################################


"001":
  totpartmass:
    min: 1.e+12
    max: null

"002":
  totpartmass:
    min: 1.e+13
    max: null

"003":
  totpartmass:
    min: 1.e+14
    max: null


################################################################################
#                        totpartmass + lambda200c                             #
################################################################################


"004":
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    min: null
    max: 0.0978  # Median of this mass threshold

"005":
  totpartmass:
    min: 1.e+12
    max: null
  lambda200c:
    min: 0.0978
    max: null

"006":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    min: null
    max: 0.0974   # Median of this mass threshold

"007":
  totpartmass:
    min: 1.e+13
    max: null
  lambda200c:
    min: 0.0974
    max: null

"008":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    min: null
    max: 0.10675  # Median of this mass threshold

"009":
  totpartmass:
    min: 1.e+14
    max: null
  lambda200c:
    min: 0.10675
    max: null
